package net.avalith.city_pass.exceptions;

public class UserNotFoundException extends RuntimeException{
    public UserNotFoundException(){super();}
}
